### ISSUE TITLE
不支持iOS吗？

### ISSUE THREAD

**Issue by 008v** [xyzxqs/XLowPoly#1]
不支持iOS吗？

**Comment by xyzxqs** [comment]
项目是 Android 的，不过核心功能是使用 C 实现的，想在 iOS 平台使用的话，需要自己移植。

**Comment by 008v** [comment]
> 项目是 Android 的，不过核心功能是使用 C 实现的，想在 iOS 平台使用的话，需要自己移植。

好吧。方便加qq嘛？讨论下delaunay算法

**Comment by xyzxqs** [comment]
我实现这个算法的时候只参考了： [Delaunay三角剖分算法](https://baike.baidu.com/item/Delaunay%E4%B8%89%E8%A7%92%E5%89%96%E5%88%86%E7%AE%97%E6%B3%95)
